
name: Node telegram bot

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: set env
        env:
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
