
name: node telegram bot

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Define variables
        run: echo "Tags are > ${TEST_ENV}"
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}
      - run: npm ci
      - run: npm run build
      - run: npm test
        env: 
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        env: 
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
